// Mock data for the Fi-CMMS application

export interface Asset {
  id: string;
  name: string;
  type: string;
  location: string;
  status: 'operational' | 'maintenance' | 'critical' | 'offline';
  healthScore: number;
  lastMaintenance: string;
  nextMaintenance: string;
  serialNumber: string;
  manufacturer: string;
  model: string;
  installDate: string;
  sensorData: number[];
}

export interface WorkOrder {
  id: string;
  assetId: string;
  assetName: string;
  title: string;
  description: string;
  status: 'open' | 'in-progress' | 'completed' | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'critical';
  assignedTo: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
  type: 'preventive' | 'corrective' | 'predictive';
  autoGenerated: boolean;
  partsUsed?: { id: string; name: string; quantity: number }[];
  laborHours?: number;
  aiDiagnosticReport?: {
    origin_analysis: string;
    tactical_steps: string[];
  };
}

export interface Technician {
  id: string;
  name: string;
  email: string;
  phone: string;
  specialization: string[];
  status: 'available' | 'busy' | 'offline';
  activeWorkOrders: number;
  completedWorkOrders: number;
  avatar: string;
}

export interface InventoryItem {
  id: string;
  name: string;
  category: string;
  quantity: number;
  minQuantity: number;
  unit: string;
  location: string;
  supplier: string;
  lastRestocked: string;
  cost: number;
}

// Generate mock sensor data with fractal properties
const generateSensorData = (baseValue: number, complexity: number): number[] => {
  const data: number[] = [];
  const points = 100;
  
  for (let i = 0; i < points; i++) {
    const noise = Math.sin(i / 5) * complexity + Math.random() * complexity * 0.5;
    const fractalNoise = Math.sin(i / 2) * 2 + Math.sin(i / 10) * 5;
    data.push(baseValue + noise + fractalNoise);
  }
  
  return data;
};

export const mockAssets: Asset[] = [
  {
    id: 'AST-001',
    name: 'Ventilator - ICU Wing A',
    type: 'Ventilator',
    location: 'ICU - Wing A, Room 102',
    status: 'operational',
    healthScore: 92,
    lastMaintenance: '2026-03-15',
    nextMaintenance: '2026-06-15',
    serialNumber: 'VNT-2024-8821',
    manufacturer: 'Medtronic',
    model: 'Puritan Bennett 980',
    installDate: '2024-01-15',
    sensorData: generateSensorData(95, 3),
  },
  {
    id: 'AST-002',
    name: 'MRI Scanner - Radiology',
    type: 'MRI Scanner',
    location: 'Radiology Department, Suite 2',
    status: 'operational',
    healthScore: 87,
    lastMaintenance: '2026-02-20',
    nextMaintenance: '2026-05-20',
    serialNumber: 'MRI-2023-4455',
    manufacturer: 'Siemens',
    model: 'MAGNETOM Vida 3T',
    installDate: '2023-06-10',
    sensorData: generateSensorData(88, 5),
  },
  {
    id: 'AST-003',
    name: 'Cardiac Monitor - CCU',
    type: 'Cardiac Monitor',
    location: 'CCU - Bed 5',
    status: 'critical',
    healthScore: 58,
    lastMaintenance: '2026-03-01',
    nextMaintenance: '2026-04-01',
    serialNumber: 'CM-2024-1122',
    manufacturer: 'Philips',
    model: 'IntelliVue MX800',
    installDate: '2024-02-01',
    sensorData: generateSensorData(60, 15),
  },
  {
    id: 'AST-004',
    name: 'Infusion Pump - Ward 3',
    type: 'Infusion Pump',
    location: 'General Ward 3, Room 304',
    status: 'maintenance',
    healthScore: 72,
    lastMaintenance: '2026-04-05',
    nextMaintenance: '2026-07-05',
    serialNumber: 'IP-2025-3344',
    manufacturer: 'BD',
    model: 'Alaris 8015',
    installDate: '2025-01-20',
    sensorData: generateSensorData(75, 8),
  },
  {
    id: 'AST-005',
    name: 'X-Ray Machine - ER',
    type: 'X-Ray',
    location: 'Emergency Room, Bay 1',
    status: 'operational',
    healthScore: 94,
    lastMaintenance: '2026-03-28',
    nextMaintenance: '2026-06-28',
    serialNumber: 'XR-2024-7788',
    manufacturer: 'GE Healthcare',
    model: 'Optima XR240amx',
    installDate: '2024-03-15',
    sensorData: generateSensorData(96, 2),
  },
  {
    id: 'AST-006',
    name: 'Anesthesia Machine - OR 2',
    type: 'Anesthesia Machine',
    location: 'Operating Room 2',
    status: 'operational',
    healthScore: 88,
    lastMaintenance: '2026-03-10',
    nextMaintenance: '2026-06-10',
    serialNumber: 'AM-2024-5566',
    manufacturer: 'Dräger',
    model: 'Fabius MRI',
    installDate: '2024-01-05',
    sensorData: generateSensorData(90, 4),
  },
  {
    id: 'AST-007',
    name: 'Defibrillator - ER Cart',
    type: 'Defibrillator',
    location: 'Emergency Room, Crash Cart 1',
    status: 'operational',
    healthScore: 96,
    lastMaintenance: '2026-04-01',
    nextMaintenance: '2026-07-01',
    serialNumber: 'DF-2025-9900',
    manufacturer: 'Zoll',
    model: 'R Series',
    installDate: '2025-02-10',
    sensorData: generateSensorData(98, 1),
  },
  {
    id: 'AST-008',
    name: 'Ultrasound - OB/GYN',
    type: 'Ultrasound',
    location: 'OB/GYN Clinic, Room 201',
    status: 'critical',
    healthScore: 62,
    lastMaintenance: '2026-02-15',
    nextMaintenance: '2026-03-15',
    serialNumber: 'US-2023-2233',
    manufacturer: 'Samsung',
    model: 'RS85',
    installDate: '2023-11-20',
    sensorData: generateSensorData(65, 12),
  },
];

export const mockWorkOrders: WorkOrder[] = [
  {
    id: 'WO-001',
    assetId: 'AST-003',
    assetName: 'Cardiac Monitor - CCU',
    title: 'AI-Predicted Maintenance Required',
    description: 'Fractal health score dropped to 58. Irregular sensor patterns detected in cardiac monitoring signals. Immediate inspection recommended.',
    status: 'open',
    priority: 'critical',
    assignedTo: null,
    createdAt: '2026-04-08T08:30:00Z',
    updatedAt: '2026-04-08T08:30:00Z',
    completedAt: null,
    type: 'predictive',
    autoGenerated: true,
    aiDiagnosticReport: {
      origin_analysis: "Stochastic resonance in the cardiac manifold suggests mechanical drift in the transducer array. Fractal dimension deviation (1.82 η) indicates non-linear signal degradation consistent with mounting fatigue.",
      tactical_steps: [
        "Inspect transducer mounting brackets for micro-fractures",
        "Calibrate signal-to-noise ratio in the G-4 sector",
        "Run 12-hour thermal stability test on the core CPU"
      ]
    }
  },
  {
    id: 'WO-002',
    assetId: 'AST-008',
    assetName: 'Ultrasound - OB/GYN',
    title: 'Degraded Signal Quality',
    description: 'AI analysis detected fractal dimension anomaly. Health score: 62. System requires calibration and component inspection.',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'Sarah Chen',
    createdAt: '2026-04-07T14:20:00Z',
    updatedAt: '2026-04-08T09:15:00Z',
    completedAt: null,
    type: 'predictive',
    autoGenerated: true,
    aiDiagnosticReport: {
      origin_analysis: "Spectral analysis of OB/GYN ultrasound node reveals significant signal attenuation in the piezoelectric crystals. The power manifold shows signs of irregular voltage ripples.",
      tactical_steps: [
        "Test voltage stability in the secondary power rail",
        "Surface-clean crystal interface with medical-grade isopropyl",
        "Verify impedance matching in the analog front-end"
      ]
    }
  },
  {
    id: 'WO-003',
    assetId: 'AST-004',
    assetName: 'Infusion Pump - Ward 3',
    title: 'Scheduled Preventive Maintenance',
    description: 'Quarterly maintenance check. Inspect flow sensors, calibrate dosage accuracy, replace filters.',
    status: 'in-progress',
    priority: 'medium',
    assignedTo: 'David Martinez',
    createdAt: '2026-04-05T10:00:00Z',
    updatedAt: '2026-04-07T16:30:00Z',
    completedAt: null,
    type: 'preventive',
    autoGenerated: false,
  },
  {
    id: 'WO-004',
    assetId: 'AST-001',
    assetName: 'Ventilator - ICU Wing A',
    title: 'Quarterly Inspection',
    description: 'Standard preventive maintenance: clean filters, check pressure sensors, verify alarm systems.',
    status: 'completed',
    priority: 'medium',
    assignedTo: 'Sarah Chen',
    createdAt: '2026-03-15T08:00:00Z',
    updatedAt: '2026-03-15T14:30:00Z',
    completedAt: '2026-03-15T14:30:00Z',
    type: 'preventive',
    autoGenerated: false,
  },
  {
    id: 'WO-005',
    assetId: 'AST-002',
    assetName: 'MRI Scanner - Radiology',
    title: 'Cooling System Check',
    description: 'Routine cooling system maintenance. Check helium levels, inspect cryogen systems.',
    status: 'completed',
    priority: 'high',
    assignedTo: 'Michael Brown',
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-02-22T17:00:00Z',
    completedAt: '2026-02-22T17:00:00Z',
    type: 'preventive',
    autoGenerated: false,
  },
  {
    id: 'WO-006',
    assetId: 'AST-006',
    assetName: 'Anesthesia Machine - OR 2',
    title: 'Calibration Required',
    description: 'Monthly calibration and safety check. Verify gas flow meters, test emergency systems.',
    status: 'open',
    priority: 'high',
    assignedTo: null,
    createdAt: '2026-04-08T07:00:00Z',
    updatedAt: '2026-04-08T07:00:00Z',
    completedAt: null,
    type: 'preventive',
    autoGenerated: false,
  },
];

export const mockTechnicians: Technician[] = [
  {
    id: 'TECH-001',
    name: 'Sarah Chen',
    email: 'sarah.chen@hospital.com',
    phone: '+254 712 345 678',
    specialization: ['Ventilators', 'Cardiac Monitors', 'Anesthesia'],
    status: 'busy',
    activeWorkOrders: 2,
    completedWorkOrders: 124,
    avatar: 'SC',
  },
  {
    id: 'TECH-002',
    name: 'David Martinez',
    email: 'david.martinez@hospital.com',
    phone: '+254 723 456 789',
    specialization: ['Infusion Pumps', 'Defibrillators', 'General Equipment'],
    status: 'busy',
    activeWorkOrders: 1,
    completedWorkOrders: 98,
    avatar: 'DM',
  },
  {
    id: 'TECH-003',
    name: 'Michael Brown',
    email: 'michael.brown@hospital.com',
    phone: '+254 734 567 890',
    specialization: ['MRI', 'X-Ray', 'Imaging Equipment'],
    status: 'available',
    activeWorkOrders: 0,
    completedWorkOrders: 156,
    avatar: 'MB',
  },
  {
    id: 'TECH-004',
    name: 'Emily Johnson',
    email: 'emily.johnson@hospital.com',
    phone: '+254 745 678 901',
    specialization: ['Ultrasound', 'Diagnostic Equipment', 'Laboratory'],
    status: 'available',
    activeWorkOrders: 0,
    completedWorkOrders: 87,
    avatar: 'EJ',
  },
  {
    id: 'TECH-005',
    name: 'James Wilson',
    email: 'james.wilson@hospital.com',
    phone: '+254 756 789 012',
    specialization: ['Surgical Equipment', 'Sterilization', 'OR Equipment'],
    status: 'offline',
    activeWorkOrders: 0,
    completedWorkOrders: 142,
    avatar: 'JW',
  },
];

export const mockInventory: InventoryItem[] = [
  {
    id: 'INV-001',
    name: 'HEPA Filters - Ventilator',
    category: 'Filters',
    quantity: 8,
    minQuantity: 15,
    unit: 'pieces',
    location: 'Central Storage, Shelf A-12',
    supplier: 'MedSupply Co.',
    lastRestocked: '2026-03-20',
    cost: 45.50,
  },
  {
    id: 'INV-002',
    name: 'ECG Electrodes',
    category: 'Consumables',
    quantity: 450,
    minQuantity: 200,
    unit: 'pieces',
    location: 'Central Storage, Bin C-5',
    supplier: 'CardioTech Ltd',
    lastRestocked: '2026-04-01',
    cost: 0.85,
  },
  {
    id: 'INV-003',
    name: 'Infusion Pump Tubing Set',
    category: 'Consumables',
    quantity: 12,
    minQuantity: 25,
    unit: 'sets',
    location: 'Pharmacy Storage',
    supplier: 'BD Medical',
    lastRestocked: '2026-03-15',
    cost: 12.30,
  },
  {
    id: 'INV-004',
    name: 'Defibrillator Pads - Adult',
    category: 'Consumables',
    quantity: 35,
    minQuantity: 20,
    unit: 'pairs',
    location: 'Emergency Storage',
    supplier: 'Zoll Medical',
    lastRestocked: '2026-04-05',
    cost: 28.00,
  },
  {
    id: 'INV-005',
    name: 'Ultrasound Gel',
    category: 'Consumables',
    quantity: 24,
    minQuantity: 30,
    unit: 'bottles',
    location: 'Radiology Storage',
    supplier: 'Parker Labs',
    lastRestocked: '2026-03-10',
    cost: 8.50,
  },
  {
    id: 'INV-006',
    name: 'Ventilator Circuit',
    category: 'Parts',
    quantity: 18,
    minQuantity: 10,
    unit: 'sets',
    location: 'ICU Storage',
    supplier: 'Medtronic',
    lastRestocked: '2026-03-28',
    cost: 67.00,
  },
  {
    id: 'INV-007',
    name: 'Blood Pressure Cuff - Adult',
    category: 'Parts',
    quantity: 42,
    minQuantity: 25,
    unit: 'pieces',
    location: 'General Storage, Shelf B-8',
    supplier: 'Philips Healthcare',
    lastRestocked: '2026-04-02',
    cost: 22.50,
  },
  {
    id: 'INV-008',
    name: 'Oxygen Sensors',
    category: 'Sensors',
    quantity: 6,
    minQuantity: 12,
    unit: 'pieces',
    location: 'Biomedical Lab',
    supplier: 'Teledyne',
    lastRestocked: '2026-02-28',
    cost: 185.00,
  },
];

// Calculate fractal dimension using box-counting method
export const calculateFractalDimension = (data: number[]): number => {
  if (data.length < 2) return 1.0;
  
  const boxSizes = [2, 4, 8, 16];
  const counts: number[] = [];
  
  for (const boxSize of boxSizes) {
    let count = 0;
    for (let i = 0; i < data.length; i += boxSize) {
      const segment = data.slice(i, i + boxSize);
      if (segment.length > 0) {
        const range = Math.max(...segment) - Math.min(...segment);
        count += Math.ceil(range / boxSize) || 1;
      }
    }
    counts.push(count);
  }
  
  // Linear regression to find slope
  const logBoxSizes = boxSizes.map(s => Math.log(1 / s));
  const logCounts = counts.map(c => Math.log(c));
  
  const n = logBoxSizes.length;
  const sumX = logBoxSizes.reduce((a, b) => a + b, 0);
  const sumY = logCounts.reduce((a, b) => a + b, 0);
  const sumXY = logBoxSizes.reduce((sum, x, i) => sum + x * logCounts[i], 0);
  const sumX2 = logBoxSizes.reduce((sum, x) => sum + x * x, 0);
  
  const slope = (n * sumXY - sumX * sumY) / (n * sumX2 - sumX * sumX);
  
  return Math.abs(slope);
};

// Calculate health score from fractal dimension
export const calculateHealthScore = (sensorData: number[]): number => {
  const fd = calculateFractalDimension(sensorData);
  
  // Normalize fractal dimension to 0-100 scale
  // Healthy signals have FD close to 1.5-1.7
  // Degraded signals have FD < 1.2 or > 2.0
  const idealFD = 1.6;
  const deviation = Math.abs(fd - idealFD);
  const healthScore = Math.max(0, Math.min(100, 100 - (deviation * 100)));
  
  return Math.round(healthScore);
};
