import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';
import { TrendingUp, Activity, Zap, AlertTriangle, Download, FileText, CheckCircle2, Globe, Layers, RefreshCw, Brain } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../components/ui/button';
import { useApp } from '../lib/store';
import { calculateFractalDimension } from '../lib/mock-data';
import { toast } from 'sonner';

export function Analytics() {
  const { assets, workOrders } = useApp();

  // Asset Status Distribution
  const statusData = [
    {
      name: 'Operational',
      value: assets.filter((a) => a.status === 'operational').length,
      color: 'var(--primary)',
    },
    {
      name: 'Maintenance',
      value: assets.filter((a) => a.status === 'maintenance').length,
      color: '#3b82f6',
    },
    {
      name: 'Critical',
      value: assets.filter((a) => a.status === 'critical').length,
      color: 'oklch(0.55 0.22 25)',
    },
    {
      name: 'Offline',
      value: assets.filter((a) => a.status === 'offline').length,
      color: '#64748b',
    },
  ];

  // Health Score Distribution
  const healthData = assets.map((asset) => ({
    name: asset.id,
    health: asset.healthScore,
    fractalDim: parseFloat(calculateFractalDimension(asset.sensorData).toFixed(3)),
  }));

  // Work Order Types
  const workOrderTypes = [
    {
      type: 'Preventive',
      count: workOrders.filter((w) => w.type === 'preventive').length,
      color: '#3b82f6',
    },
    {
      type: 'Corrective',
      count: workOrders.filter((w) => w.type === 'corrective').length,
      color: '#f59e0b',
    },
    {
      type: 'Predictive (AI)',
      count: workOrders.filter((w) => w.type === 'predictive').length,
      color: 'var(--primary)',
    },
  ];

  // Monthly Trends
  const currentMonthWorkOrders = workOrders.length;
  const currentMonthAiGenerated = workOrders.filter(w => w.autoGenerated).length;
  const currentMonthAvgHealth = assets.length > 0 
    ? Math.round(assets.reduce((sum, a) => sum + a.healthScore, 0) / assets.length)
    : 0;

  const monthlyData = [
    { month: 'JAN', workOrders: 12, aiGenerated: 2, avgHealth: 88, neuralDrift: 0.12 },
    { month: 'FEB', workOrders: 15, aiGenerated: 3, avgHealth: 86, neuralDrift: 0.15 },
    { month: 'MAR', workOrders: 10, aiGenerated: 1, avgHealth: 89, neuralDrift: 0.08 },
    { month: 'APR', workOrders: Math.max(currentMonthWorkOrders, 8), aiGenerated: currentMonthAiGenerated, avgHealth: currentMonthAvgHealth || 90, neuralDrift: 0.05 },
  ];

  const avgHealthScore = assets.length > 0 
    ? Math.round(assets.reduce((sum, a) => sum + a.healthScore, 0) / assets.length)
    : 0;

  const totalAiOrders = workOrders.filter((w) => w.autoGenerated).length;
  const completedAiOrders = workOrders.filter((w) => w.autoGenerated && w.status === 'completed').length;
  
  const aiEffectiveness = totalAiOrders > 0
    ? Math.round((completedAiOrders / totalAiOrders) * 100)
    : 0;

  return (
    <div className="space-y-8 pb-12">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
        <div>
          <h2 className="text-3xl font-bold tracking-tighter glow-text bg-clip-text text-transparent bg-gradient-to-r from-primary to-blue-400 uppercase italic">
            NEURAL_TELEMETRY
          </h2>
          <p className="text-muted-foreground flex items-center gap-2 mt-1 uppercase tracking-widest text-[10px] font-bold opacity-60">
            <Activity className="w-4 h-4 text-primary" />
            Predictive Manifold & System Integrity Analytics
          </p>
        </div>
        <div className="flex gap-2">
          <Button 
            className="rounded-xl shadow-lg shadow-primary/20 bg-primary/10 border border-primary/20 text-primary hover:bg-primary/20"
            onClick={() => {
              toast.info('Synthesizing manifest report...', { icon: <FileText className="w-4 h-4" /> });
              setTimeout(() => {
                toast.success('CORE_LEDGER_EXPORTED_04.XLSX', {
                  icon: <CheckCircle2 className="w-4 h-4 text-primary" />
                });
              }, 2000);
            }}
          >
            <Download className="w-4 h-4 mr-2" />
            EXPORT_LOGS
          </Button>
        </div>
      </div>

      {/* Key Metrics Cluster */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <MetricTile icon={Activity} label="System Integrity" value={`${avgHealthScore}%`} trend="+3.2%" status="nominal" />
        <MetricTile icon={Zap} label="Neural Pipeline" value={totalAiOrders} trend="LIVE" status="active" />
        <MetricTile icon={AlertTriangle} label="Breach Warnings" value={assets.filter((a) => a.healthScore < 70).length} trend="CRITICAL" status="warning" />
        <MetricTile icon={CheckCircle2} label="Resolved Ops" value={workOrders.filter((w) => w.status === 'completed').length} trend="+12" status="success" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Status Distribution */}
        <Card className="lg:col-span-5 glass-panel border-none">
          <CardHeader>
            <CardTitle className="text-xs font-black uppercase tracking-[0.2em] italic text-primary flex items-center gap-2">
               <Globe className="w-4 h-4" />
               Node_Status_Manifold
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Tooltip 
                    contentStyle={{ backgroundColor: 'rgba(5, 5, 20, 0.9)', border: '1px solid rgba(139, 92, 246, 0.3)', borderRadius: '12px' }}
                  />
                  <Pie
                    data={statusData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={100}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {statusData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} stroke="none" />
                    ))}
                  </Pie>
                  <Legend iconType="circle" wrapperStyle={{ paddingTop: '20px', fontSize: '10px', textTransform: 'uppercase', fontStyle: 'italic' }} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        {/* Work Order Manifold */}
        <Card className="lg:col-span-7 glass-panel border-none">
          <CardHeader>
            <CardTitle className="text-xs font-black uppercase tracking-[0.2em] italic text-primary flex items-center gap-2">
               <Layers className="w-4 h-4" />
               Deployment_Classification
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={workOrderTypes}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff05" vertical={false} />
                  <XAxis dataKey="type" stroke="#ffffff20" fontSize={10} axisLine={false} tickLine={false} />
                  <YAxis stroke="#ffffff20" fontSize={10} axisLine={false} tickLine={false} />
                  <Tooltip
                    cursor={{fill: 'rgba(255,255,255,0.02)'}}
                    contentStyle={{ backgroundColor: 'rgba(5, 5, 20, 0.95)', border: '1px solid rgba(139, 92, 246, 0.3)', borderRadius: '12px' }}
                  />
                  <Bar dataKey="count" radius={[4, 4, 0, 0]}>
                    {workOrderTypes.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        {/* Fractal Health Overload */}
        <Card className="lg:col-span-12 glass-panel border-none">
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="text-xs font-black uppercase tracking-[0.2em] italic text-primary flex items-center gap-4">
               <Activity className="w-4 h-4" />
               Node_Health_Telemetry & Fractal_Divergence
            </CardTitle>
            <Badge variant="outline" className="text-[9px] border-primary/20 opacity-40">SIGNAL_LOCK_ACTIVE</Badge>
          </CardHeader>
          <CardContent>
            <div className="h-96">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={healthData} margin={{ top: 20, right: 30, left: 20, bottom: 60 }}>
                  <defs>
                    <linearGradient id="healthGrad" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="var(--primary)" stopOpacity={0.8}/>
                      <stop offset="95%" stopColor="var(--primary)" stopOpacity={0.1}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff05" vertical={false} />
                  <XAxis dataKey="name" stroke="#ffffff20" fontSize={9} angle={-45} textAnchor="end" interval={0} axisLine={false} tickLine={false} />
                  <YAxis stroke="#ffffff20" fontSize={10} domain={[0, 100]} axisLine={false} tickLine={false} />
                  <Tooltip
                    contentStyle={{ backgroundColor: 'rgba(5, 5, 20, 0.95)', border: '1px solid rgba(139, 92, 246, 0.3)', borderRadius: '12px' }}
                  />
                  <Bar dataKey="health" fill="url(#healthGrad)" radius={[4, 4, 0, 0]} name="Integrity_Index" />
                  <Bar dataKey="fractalDim" fill="#3b82f6" radius={[4, 4, 0, 0]} name="Fractal_Complexity" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        {/* Neural Trend Cluster */}
        <Card className="lg:col-span-12 glass-panel border-none">
          <CardHeader>
            <CardTitle className="text-xs font-black uppercase tracking-[0.2em] italic text-primary flex items-center gap-2">
               <RefreshCw className="w-4 h-4" />
               Temporal_Neural_Convergence
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-96">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={monthlyData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff05" vertical={false} />
                  <XAxis dataKey="month" stroke="#ffffff20" fontSize={10} axisLine={false} tickLine={false} />
                  <YAxis stroke="#ffffff20" fontSize={10} axisLine={false} tickLine={false} />
                  <Tooltip
                    contentStyle={{ backgroundColor: 'rgba(5, 5, 20, 0.95)', border: '1px solid rgba(139, 92, 246, 0.3)', borderRadius: '12px' }}
                  />
                  <Legend iconType="rect" wrapperStyle={{ fontSize: '10px', textTransform: 'uppercase', color: '#fff' }} />
                  <Line type="monotone" dataKey="workOrders" stroke="#3b82f6" strokeWidth={3} dot={{ r: 4, fill: '#3b82f6' }} name="OPS_VOLUME" />
                  <Line type="monotone" dataKey="aiGenerated" stroke="var(--primary)" strokeWidth={3} dot={{ r: 4, fill: 'var(--primary)' }} name="AI_INJECTED" />
                  <Line type="monotone" dataKey="neuralDrift" stroke="oklch(0.55 0.22 25)" strokeWidth={3} dot={{ r: 4, fill: 'oklch(0.55 0.22 25)' }} name="NEURAL_DRIFT" />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* AI Intelligence Briefing */}
      <Card className="glass-panel border-primary/20 bg-primary/5 relative overflow-hidden group">
        <div className="absolute inset-0 bg-gradient-to-r from-primary/10 to-transparent pointer-events-none" />
        <CardHeader>
          <CardTitle className="flex items-center gap-3 text-primary text-xl font-black italic tracking-tighter uppercase">
            <Zap className="w-8 h-8 animate-pulse text-amber-400" />
            Oracle_Intelligence_Briefing
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative">
            <IntelligenceBox 
               label="Predictive Engine Accuracy" 
               value="94.2%" 
               sub="Refined via 4.2M simulation cycles" 
               color="primary"
            />
            <IntelligenceBox 
               label="Early Warning Interval" 
               value="12.4 hrs" 
               sub="Mean detection time before breach" 
               color="success"
            />
            <IntelligenceBox 
               label="System Neural Density" 
               value="0.842 η" 
               sub="High connectivity across all nodes" 
               color="info"
            />
          </div>
          <div className="mt-8 p-6 rounded-3xl bg-black/40 border border-white/5 relative group">
             <div className="absolute -right-4 -top-4 opacity-5 group-hover:opacity-10 transition-opacity">
                <Brain className="w-32 h-32" />
             </div>
             <p className="text-xs uppercase font-black text-primary italic mb-3 tracking-[0.3em]">Oracle_Core_Directive</p>
             <p className="text-sm italic text-blue-100/70 leading-relaxed max-w-4xl">
               Current system state is highly stable within the 4th dimensional manifold. Fractal analysis suggests material fatigue in sector G-04 (Imaging) within the next 42 operational hours. Neural drift is minimal, indicating a high-fidelity sync between the Sentinel Engine and edge sensors. Maintenance escalation for MRI_CORE_04 is recommended to maintain 99.9% uptime.
             </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function MetricTile({ icon: Icon, label, value, trend, status }: any) {
  const statusColor: any = {
    nominal: 'text-primary border-primary/20 bg-primary/5',
    active: 'text-blue-400 border-blue-400/20 bg-blue-400/5',
    warning: 'text-destructive border-destructive/20 bg-destructive/5',
    success: 'text-green-500 border-green-500/20 bg-green-500/5',
  };

  return (
    <div className={`nexus-node p-6 border ${statusColor[status]} relative overflow-hidden group`}>
      <div className="absolute -right-2 -bottom-2 opacity-5 group-hover:opacity-10 transition-opacity">
         <Icon className="w-16 h-16" />
      </div>
      <div className="flex items-center justify-between mb-4">
        <Icon className="w-5 h-5 opacity-80" />
        <span className="text-[10px] font-black italic tracking-widest bg-white/5 px-2 py-0.5 rounded-full">{trend}</span>
      </div>
      <p className="text-3xl font-mono font-black italic tracking-tighter mb-1">{value}</p>
      <p className="text-[10px] font-bold uppercase tracking-widest opacity-40">{label}</p>
    </div>
  );
}

function IntelligenceBox({ label, value, sub, color }: any) {
  return (
    <div className="nexus-node p-5 border-white/10 relative group bg-black/40">
       <div className="absolute top-0 left-0 w-1 h-full bg-primary/40 group-hover:bg-primary transition-colors" />
       <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mb-1 opacity-60">{label}</p>
       <p className="text-3xl font-mono font-black text-primary italic tracking-tight mb-2">{value}</p>
       <p className="text-[10px] text-muted-foreground opacity-40 italic">{sub}</p>
    </div>
  );
}
