import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';
import { TrendingUp, Activity, Zap, AlertTriangle, Download, FileText, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../components/ui/button';
import { useApp } from '../lib/store';
import { calculateFractalDimension } from '../lib/mock-data';
import { toast } from 'sonner';

export function Analytics() {
  const { assets, workOrders } = useApp();

  // Asset Status Distribution
  const statusData = [
    {
      name: 'Operational',
      value: assets.filter((a) => a.status === 'operational').length,
      color: '#10b981',
    },
    {
      name: 'Maintenance',
      value: assets.filter((a) => a.status === 'maintenance').length,
      color: '#3b82f6',
    },
    {
      name: 'Critical',
      value: assets.filter((a) => a.status === 'critical').length,
      color: '#ef4444',
    },
    {
      name: 'Offline',
      value: assets.filter((a) => a.status === 'offline').length,
      color: '#64748b',
    },
  ];

  // Health Score Distribution
  const healthData = assets.map((asset) => ({
    name: asset.id,
    health: asset.healthScore,
    fractalDim: calculateFractalDimension(asset.sensorData).toFixed(3),
  }));

  // Work Order Types
  const workOrderTypes = [
    {
      type: 'Preventive',
      count: workOrders.filter((w) => w.type === 'preventive').length,
      color: '#3b82f6',
    },
    {
      type: 'Corrective',
      count: workOrders.filter((w) => w.type === 'corrective').length,
      color: '#f59e0b',
    },
    {
      type: 'Predictive (AI)',
      count: workOrders.filter((w) => w.type === 'predictive').length,
      color: '#8b5cf6',
    },
  ];

  // Monthly Trends (calculated from real data for current month)
  const currentMonthWorkOrders = workOrders.length;
  const currentMonthAiGenerated = workOrders.filter(w => w.autoGenerated).length;
  const currentMonthAvgHealth = assets.length > 0 
    ? Math.round(assets.reduce((sum, a) => sum + a.healthScore, 0) / assets.length)
    : 0;

  const monthlyData = [
    { month: 'Jan', workOrders: 12, aiGenerated: 2, avgHealth: 88 },
    { month: 'Feb', workOrders: 15, aiGenerated: 3, avgHealth: 86 },
    { month: 'Mar', workOrders: 10, aiGenerated: 1, avgHealth: 89 },
    { month: 'Apr', workOrders: Math.max(currentMonthWorkOrders, 8), aiGenerated: currentMonthAiGenerated, avgHealth: currentMonthAvgHealth || 90 },
  ];

  const avgHealthScore = assets.length > 0 
    ? Math.round(assets.reduce((sum, a) => sum + a.healthScore, 0) / assets.length)
    : 0;

  const totalAiOrders = workOrders.filter((w) => w.autoGenerated).length;
  const completedAiOrders = workOrders.filter((w) => w.autoGenerated && w.status === 'completed').length;
  
  const aiEffectiveness = totalAiOrders > 0
    ? Math.round((completedAiOrders / totalAiOrders) * 100)
    : 0;

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Analytics & Insights</h2>
          <p className="text-slate-500">System performance and AI predictive maintenance metrics</p>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            onClick={() => {
              toast.info('Generating PDF report...', { icon: <FileText className="w-4 h-4" /> });
              setTimeout(() => {
                toast.success('Performance Report exported successfully!', {
                  icon: <CheckCircle2 className="w-4 h-4 text-green-500" />
                });
              }, 2000);
            }}
          >
            <Download className="w-4 h-4 mr-2" />
            Export Report
          </Button>
        </div>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <Activity className="w-8 h-8 text-blue-600" />
            </div>
            <p className="text-2xl font-bold text-slate-900">{avgHealthScore}%</p>
            <p className="text-sm text-slate-500">Avg Health Score</p>
            <div className="flex items-center gap-1 mt-2 text-xs text-green-600">
              <TrendingUp className="w-3 h-3" />
              <span>+3% vs last month</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <Zap className="w-8 h-8 text-purple-600" />
            </div>
            <p className="text-2xl font-bold text-slate-900">{totalAiOrders}</p>
            <p className="text-sm text-slate-500">AI-Generated Orders</p>
            <div className="flex items-center gap-1 mt-2 text-xs text-purple-600">
              <span>{aiEffectiveness}% completion rate</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <AlertTriangle className="w-8 h-8 text-red-600" />
            </div>
            <p className="text-2xl font-bold text-slate-900">
              {assets.filter((a) => a.healthScore < 70).length}
            </p>
            <p className="text-sm text-slate-500">Critical Assets</p>
            <div className="flex items-center gap-1 mt-2 text-xs text-red-600">
              <span>Requires attention</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <TrendingUp className="w-8 h-8 text-green-600" />
            </div>
            <p className="text-2xl font-bold text-slate-900">
              {workOrders.filter((w) => w.status === 'completed').length}
            </p>
            <p className="text-sm text-slate-500">Completed Orders</p>
            <div className="flex items-center gap-1 mt-2 text-xs text-green-600">
              <TrendingUp className="w-3 h-3" />
              <span>{Math.round((workOrders.filter(w => w.status === 'completed').length / (workOrders.length || 1)) * 100)}% completion rate</span>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Asset Status Distribution */}
        <Card>
          <CardHeader>
            <CardTitle>Asset Status Distribution</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={statusData}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={({ name, value }) => value > 0 ? `${name}: ${value}` : ''}
                    outerRadius={100}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {statusData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        {/* Work Order Types */}
        <Card>
          <CardHeader>
            <CardTitle>Work Order Types</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={workOrderTypes}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="type" stroke="#64748b" fontSize={12} />
                  <YAxis stroke="#64748b" fontSize={12} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: 'white',
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                    }}
                  />
                  <Bar dataKey="count" fill="#3b82f6" radius={[8, 8, 0, 0]}>
                    {workOrderTypes.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Health Score Overview */}
      <Card>
        <CardHeader>
          <CardTitle>Equipment Health Score Overview</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={healthData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis dataKey="name" stroke="#64748b" fontSize={10} angle={-45} textAnchor="end" height={60} />
                <YAxis stroke="#64748b" fontSize={12} domain={[0, 100]} />
                <Tooltip
                  contentStyle={{
                    backgroundColor: 'white',
                    border: '1px solid #e2e8f0',
                    borderRadius: '8px',
                  }}
                  formatter={(value: any, name: any) => [
                    name === 'health' ? `${value}%` : value,
                    name === 'health' ? 'Health Score' : 'Fractal Dimension',
                  ]}
                />
                <Legend />
                <Bar
                  dataKey="health"
                  fill="#10b981"
                  radius={[4, 4, 0, 0]}
                  name="Health Score"
                />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>

      {/* Monthly Trends */}
      <Card>
        <CardHeader>
          <CardTitle>Monthly Maintenance Trends</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={monthlyData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis dataKey="month" stroke="#64748b" fontSize={12} />
                <YAxis stroke="#64748b" fontSize={12} />
                <Tooltip
                  contentStyle={{
                    backgroundColor: 'white',
                    border: '1px solid #e2e8f0',
                    borderRadius: '8px',
                  }}
                />
                <Legend />
                <Line
                  type="monotone"
                  dataKey="workOrders"
                  stroke="#3b82f6"
                  strokeWidth={2}
                  name="Total Work Orders"
                />
                <Line
                  type="monotone"
                  dataKey="aiGenerated"
                  stroke="#8b5cf6"
                  strokeWidth={2}
                  name="AI-Generated"
                />
                <Line
                  type="monotone"
                  dataKey="avgHealth"
                  stroke="#10b981"
                  strokeWidth={2}
                  name="Avg Health Score"
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>

      {/* AI Performance */}
      <Card className="border-purple-200 bg-purple-50">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-purple-900">
            <Zap className="w-5 h-5" />
            AI Predictive Maintenance Performance
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-4 bg-white rounded-lg border border-purple-200">
              <p className="text-sm text-purple-700 mb-1">Fractal Analysis Accuracy</p>
              <p className="text-2xl font-bold text-purple-900">94.2%</p>
              <p className="text-xs text-purple-600 mt-1">Based on box-counting algorithm</p>
            </div>
            <div className="p-4 bg-white rounded-lg border border-purple-200">
              <p className="text-sm text-purple-700 mb-1">Early Detection Rate</p>
              <p className="text-2xl font-bold text-purple-900">87%</p>
              <p className="text-xs text-purple-600 mt-1">Failures predicted before occurrence</p>
            </div>
            <div className="p-4 bg-white rounded-lg border border-purple-200">
              <p className="text-sm text-purple-700 mb-1">False Positive Rate</p>
              <p className="text-2xl font-bold text-purple-900">8.3%</p>
              <p className="text-xs text-purple-600 mt-1">Below 10% target threshold</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
