import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Progress } from '../components/ui/progress';
import {
  Activity,
  AlertTriangle,
  CheckCircle2,
  Clock,
  TrendingUp,
  Zap,
  Package,
  Wrench,
} from 'lucide-react';
import { useApp } from '../lib/store';
import { Link } from 'react-router';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '../components/ui/dialog';
import { AssetForm } from '../components/forms/AssetForm';
import { WorkOrderForm } from '../components/forms/WorkOrderForm';

export function Dashboard() {
  const { assets, workOrders, inventory } = useApp();
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [assetModalOpen, setAssetModalOpen] = useState(false);
  const [workOrderModalOpen, setWorkOrderModalOpen] = useState(false);

  const criticalAssets = assets.filter((a) => a.healthScore < 65);
  const openWorkOrders = workOrders.filter((w) => w.status === 'open');
  const inProgressWorkOrders = workOrders.filter((w) => w.status === 'in-progress');
  const lowStockItems = inventory.filter((i) => i.quantity < i.minQuantity);
  const aiGeneratedOrders = workOrders.filter((w) => w.autoGenerated);

  const stats = [
    {
      title: 'Total Assets',
      value: assets.length.toString(),
      change: '+2 this month',
      icon: Package,
      color: 'text-blue-600',
      bg: 'bg-blue-100',
    },
    {
      title: 'Critical Alerts',
      value: criticalAssets.length.toString(),
      change: 'Requires attention',
      icon: AlertTriangle,
      color: 'text-red-600',
      bg: 'bg-red-100',
    },
    {
      title: 'Open Work Orders',
      value: openWorkOrders.length.toString(),
      change: `${aiGeneratedOrders.filter(w => w.status === 'open').length} AI-generated`,
      icon: Clock,
      color: 'text-amber-600',
      bg: 'bg-amber-100',
    },
    {
      title: 'In Progress',
      value: inProgressWorkOrders.length.toString(),
      change: 'Active tasks',
      icon: Wrench,
      color: 'text-green-600',
      bg: 'bg-green-100',
    },
  ];

  const allNotifications = [
    ...criticalAssets.map(a => ({ type: 'critical', message: `${a.name} has health score ${a.healthScore}%`, time: 'Now' })),
    ...lowStockItems.map(i => ({ type: 'warning', message: `${i.name} is below minimum stock (${i.quantity}/${i.minQuantity} ${i.unit})`, time: 'Now' })),
    ...openWorkOrders.filter(w => w.autoGenerated).map(w => ({ type: 'ai', message: `AI generated work order: ${w.title}`, time: new Date(w.createdAt).toLocaleTimeString() })),
  ];

  return (
    <div className="space-y-6">
      {/* AI Alert Banner */}
      {criticalAssets.length > 0 && (
        <Card className="border-red-200 bg-red-50">
          <CardContent className="p-4">
            <div className="flex items-start gap-3">
              <div className="w-10 h-10 bg-red-600 rounded-lg flex items-center justify-center flex-shrink-0">
                <Zap className="w-5 h-5 text-white" />
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <h3 className="font-semibold text-red-900">
                    AI Predictive Maintenance Alert
                  </h3>
                  <Badge variant="destructive">Critical</Badge>
                </div>
                <p className="text-sm text-red-700 mb-2">
                  Fractal analysis detected {criticalAssets.length} equipment health score{criticalAssets.length > 1 ? 's' : ''} below the documentation's 65% safety threshold. Automatic
                  work orders have been generated for immediate inspection.
                </p>
                <div className="flex gap-2">
                  <Link to="/work-orders">
                    <Button size="sm" variant="destructive">
                      View Work Orders
                    </Button>
                  </Link>
                  <Button size="sm" variant="outline" className="bg-white" onClick={() => setNotificationsOpen(true)}>
                    View All Alerts ({allNotifications.length})
                  </Button>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <Card key={stat.title}>
              <CardContent className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className={`w-12 h-12 rounded-lg ${stat.bg} flex items-center justify-center`}>
                    <Icon className={`w-6 h-6 ${stat.color}`} />
                  </div>
                </div>
                <div className="space-y-1">
                  <p className="text-sm text-slate-500">{stat.title}</p>
                  <p className="text-3xl font-bold text-slate-900">{stat.value}</p>
                  <p className="text-xs text-slate-500">{stat.change}</p>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Critical Assets */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-red-600" />
              Critical Assets Requiring Attention
            </CardTitle>
          </CardHeader>
          <CardContent>
            {criticalAssets.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <CheckCircle2 className="w-12 h-12 text-green-500 mb-2" />
                <p className="text-slate-600 font-medium">All assets are healthy!</p>
                <p className="text-sm text-slate-400">No critical equipment detected.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {criticalAssets.map((asset) => (
                  <div key={asset.id} className="flex items-start gap-3 p-3 rounded-lg border border-slate-200">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <p className="font-medium text-slate-900 truncate">{asset.name}</p>
                        <Badge variant={asset.healthScore < 65 ? 'destructive' : 'default'}>
                          {asset.healthScore}% Health
                        </Badge>
                      </div>
                      <p className="text-sm text-slate-500">{asset.location}</p>
                      <div className="mt-2">
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-xs text-slate-500">Fractal Health Score</span>
                          <span className="text-xs font-medium">{asset.healthScore}%</span>
                        </div>
                        <Progress
                          value={asset.healthScore}
                          className={asset.healthScore < 65 ? 'bg-red-100' : 'bg-amber-100'}
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Recent Work Orders */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Activity className="w-5 h-5 text-blue-600" />
              Recent Work Orders
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {workOrders.slice(0, 4).map((order) => (
                <div
                  key={order.id}
                  className="flex items-start gap-3 p-3 rounded-lg border border-slate-200"
                >
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <p className="font-medium text-slate-900 truncate">{order.title}</p>
                      {order.autoGenerated && (
                        <Badge variant="secondary" className="flex items-center gap-1">
                          <Zap className="w-3 h-3" />
                          AI
                        </Badge>
                      )}
                    </div>
                    <p className="text-sm text-slate-500 mb-2">{order.assetName}</p>
                    <div className="flex items-center gap-2">
                      <Badge
                        variant={
                          order.priority === 'critical'
                            ? 'destructive'
                            : order.priority === 'high'
                            ? 'default'
                            : 'secondary'
                        }
                      >
                        {order.priority}
                      </Badge>
                      <Badge
                        variant={
                          order.status === 'completed'
                            ? 'outline'
                            : order.status === 'in-progress'
                            ? 'default'
                            : 'secondary'
                        }
                      >
                        {order.status}
                      </Badge>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-4">
              <Link to="/work-orders">
                <Button variant="outline" size="sm" className="w-full">View All Work Orders</Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Low Stock Alert */}
      {lowStockItems.length > 0 && (
        <Card className="border-amber-200 bg-amber-50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-amber-900">
              <AlertTriangle className="w-5 h-5" />
              Low Stock Alert
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {lowStockItems.slice(0, 3).map((item) => (
                <div key={item.id} className="p-3 bg-white rounded-lg border border-amber-200">
                  <p className="font-medium text-slate-900 mb-1">{item.name}</p>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-slate-500">
                      Stock: {item.quantity}/{item.minQuantity}
                    </span>
                    <Badge variant="outline">Restock needed</Badge>
                  </div>
                </div>
              ))}
            </div>
            {lowStockItems.length > 3 && (
              <div className="mt-3">
                <Link to="/inventory">
                  <Button variant="outline" size="sm" className="bg-white">
                    View All ({lowStockItems.length} items)
                  </Button>
                </Link>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Quick Actions */}
      <Card>
        <CardHeader>
          <CardTitle>Quick Actions</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
            <Button variant="outline" className="w-full justify-start" onClick={() => setAssetModalOpen(true)}>
              <Package className="w-4 h-4 mr-2 text-blue-600" />
              Register Asset
            </Button>
            <Button variant="outline" className="w-full justify-start" onClick={() => setWorkOrderModalOpen(true)}>
              <Wrench className="w-4 h-4 mr-2 text-amber-600" />
              Create Work Order
            </Button>
            <Link to="/analytics">
              <Button variant="outline" className="w-full justify-start">
                <TrendingUp className="w-4 h-4 mr-2 text-purple-600" />
                View Analytics
              </Button>
            </Link>
            <Link to="/inventory">
              <Button variant="outline" className="w-full justify-start">
                <CheckCircle2 className="w-4 h-4 mr-2 text-green-600" />
                Manage Inventory
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>

      {/* Quick Action Modals */}
      <Dialog open={assetModalOpen} onOpenChange={setAssetModalOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Quick Asset Registration</DialogTitle>
          </DialogHeader>
          <AssetForm onSuccess={() => setAssetModalOpen(false)} />
        </DialogContent>
      </Dialog>

      <Dialog open={workOrderModalOpen} onOpenChange={setWorkOrderModalOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Quick Maintenance Assignment</DialogTitle>
          </DialogHeader>
          <WorkOrderForm onSuccess={() => setWorkOrderModalOpen(false)} />
        </DialogContent>
      </Dialog>

      {/* Notifications Dialog */}
      <Dialog open={notificationsOpen} onOpenChange={setNotificationsOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-red-600" />
              All System Alerts ({allNotifications.length})
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-3 max-h-80 overflow-y-auto">
            {allNotifications.length === 0 ? (
              <p className="text-slate-500 text-center py-4">No alerts at this time.</p>
            ) : (
              allNotifications.map((n, i) => (
                <div
                  key={i}
                  className={`p-3 rounded-lg border text-sm ${
                    n.type === 'critical'
                      ? 'bg-red-50 border-red-200 text-red-800'
                      : n.type === 'ai'
                      ? 'bg-purple-50 border-purple-200 text-purple-800'
                      : 'bg-amber-50 border-amber-200 text-amber-800'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <p>{n.message}</p>
                    <span className="text-xs opacity-60 whitespace-nowrap">{n.time}</span>
                  </div>
                </div>
              ))
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
