import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Activity, 
  AlertTriangle, 
  Zap, 
  ShieldCheck, 
  Cpu, 
  Globe, 
  TrendingUp,
  Box
} from 'lucide-react';
import { useApp } from '../lib/store';
import { Progress } from '../components/ui/progress';
import { Badge } from '../components/ui/badge';
import { Card, CardContent } from '../components/ui/card';

export function NexusDashboard() {
  const { assets, workOrders, inventory } = useApp();
  const [activeStream, setActiveStream] = useState<string[]>([]);
  
  // Simulated "AI Mind" Stream
  useEffect(() => {
    const intervals = [
      "Analyzing fractal variance in MRI-001...",
      "Quantum state: STABLE",
      "Network latency: 1.2ms",
      "Predictive model confidence: 98.4%",
      "Box-count dimension recalculating...",
      "Sentinel Oracle: ACTIVE"
    ];
    
    const timer = setInterval(() => {
      setActiveStream(prev => [intervals[Math.floor(Math.random() * intervals.length)], ...prev].slice(0, 8));
    }, 3000);
    
    return () => clearInterval(timer);
  }, []);

  const criticalAssets = assets.filter(a => a.healthScore < 65);
  const openWorkOrders = workOrders.filter(w => w.status === 'open');

  return (
    <div className="space-y-8 pb-12">
      {/* Header HUD */}
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-4xl font-bold tracking-tighter glow-text bg-clip-text text-transparent bg-gradient-to-r from-primary to-blue-400">
            NEXUS COMMAND
          </h1>
          <p className="text-muted-foreground flex items-center gap-2">
            <Globe className="w-4 h-4 text-primary animate-pulse" />
            Global Facility Intelligence Overlook
          </p>
        </div>
        
        <div className="flex items-center gap-3">
          <div className="glass-panel px-4 py-2 rounded-full flex items-center gap-2 text-xs font-mono border-primary/20">
            <div className="w-2 h-2 rounded-full bg-green-500 animate-ping" />
            ENCRYPTED LINK: SECURE
          </div>
          <div className="glass-panel px-4 py-2 rounded-full flex items-center gap-2 text-xs font-mono border-primary/20">
            <Cpu className="w-4 h-4 text-primary" />
            SENTINEL ORACLE: ONLINE
          </div>
        </div>
      </header>

      {/* Primary HUD Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Col: Core Pulse */}
        <div className="lg:col-span-8 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <StatNode 
              icon={Activity} 
              label="Asset Pulse" 
              value={`${Math.round(assets.reduce((acc, a) => acc + a.healthScore, 0) / assets.length)}%`} 
              sub="Facility Avg"
              color="primary"
            />
            <StatNode 
              icon={Zap} 
              label="Predictive Hits" 
              value={workOrders.filter(w => w.autoGenerated).length.toString()} 
              sub="AI Detected"
              color="warning"
            />
            <StatNode 
              icon={ShieldCheck} 
              label="Site Integrity" 
              value="AAA" 
              sub="Gold Standard"
              color="success"
            />
          </div>

          <Card className="glass-panel overflow-hidden border-none">
            <CardContent className="p-0">
              <div className="bg-primary/5 p-4 border-b border-white/5 flex items-center justify-between">
                <h3 className="text-sm font-semibold flex items-center gap-2">
                  <Activity className="w-4 h-4 text-primary" />
                  Facility Heartbeat (Real-time)
                </h3>
              </div>
              <div className="p-8 h-64 flex items-end justify-between gap-1 group">
                {assets.map((asset, i) => (
                  <motion.div 
                    key={asset.id}
                    className="flex-1 flex flex-col items-center gap-2"
                    initial={{ height: 0 }}
                    animate={{ height: `${asset.healthScore}%` }}
                    transition={{ delay: i * 0.1, duration: 1, ease: "circOut" }}
                  >
                    <div 
                      className={`w-full rounded-t-lg relative group-hover:opacity-50 hover:!opacity-100 transition-opacity cursor-help ${
                        asset.healthScore < 65 ? 'bg-destructive shadow-[0_0_15px_oklch(0.55_0.22_25/0.4)]' : 'bg-primary shadow-[0_0_15px_oklch(0.65_0.22_260/0.4)]'
                      }`}
                    >
                      <div className="absolute -top-8 left-1/2 -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap text-[10px] font-mono bg-background px-2 py-1 rounded-md border border-white/10">
                        {asset.name}: {asset.healthScore}%
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </CardContent>
          </Card>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
             <Card className="glass-panel border-none">
                <CardContent className="p-6">
                  <h3 className="text-sm font-semibold mb-4 flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4 text-destructive" />
                    Neural Anomalies
                  </h3>
                  <div className="space-y-4">
                    {criticalAssets.map(asset => (
                      <div key={asset.id} className="flex items-center justify-between p-3 rounded-xl bg-white/5 border border-white/5">
                        <div>
                          <p className="text-sm font-medium">{asset.name}</p>
                          <p className="text-[10px] text-muted-foreground uppercase">{asset.location}</p>
                        </div>
                        <Badge variant="destructive" className="animate-pulse">
                          {asset.healthScore}% Critical
                        </Badge>
                      </div>
                    ))}
                  </div>
                </CardContent>
             </Card>
             
             <Card className="glass-panel border-none bg-primary/5">
                <CardContent className="p-6">
                  <h3 className="text-sm font-semibold mb-4 flex items-center gap-2">
                    <TrendingUp className="w-4 h-4 text-primary" />
                    Resource Optimization
                  </h3>
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <div className="flex justify-between text-xs">
                        <span className="text-muted-foreground">Inventory Utilization</span>
                        <span>84%</span>
                      </div>
                      <Progress value={84} className="h-1 bg-white/5" />
                    </div>
                    <div className="space-y-2">
                      <div className="flex justify-between text-xs">
                        <span className="text-muted-foreground">Technician Efficiency</span>
                        <span>92%</span>
                      </div>
                      <Progress value={92} className="h-1 bg-white/5" />
                    </div>
                  </div>
                </CardContent>
             </Card>
          </div>
        </div>

        {/* Right Col: AI Mind */}
        <div className="lg:col-span-4 space-y-6">
          <Card className="glass-panel border-none h-full flex flex-col">
            <CardContent className="p-6 flex flex-col h-full">
               <div className="flex items-center gap-3 mb-6">
                 <div className="w-10 h-10 rounded-xl bg-primary/20 flex items-center justify-center">
                   <Zap className="w-6 h-6 text-primary glow-text" />
                 </div>
                 <div>
                   <h3 className="font-bold">SENTINEL_ORACLE</h3>
                   <p className="text-[10px] text-muted-foreground">AI COGNITIVE STREAM</p>
                 </div>
               </div>
               
               <div className="flex-1 bg-black/40 rounded-2xl p-4 font-mono text-[11px] space-y-3 overflow-hidden border border-white/5">
                 <AnimatePresence initial={false}>
                   {activeStream.map((log, i) => (
                     <motion.div 
                        key={log + i}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1 - (i * 0.1), x: 0 }}
                        className="flex gap-2"
                     >
                       <span className="text-primary italic">[{new Date().toLocaleTimeString([], { hour12: false })}]</span>
                       <span className={log.includes('CRITICAL') ? 'text-destructive' : 'text-blue-200'}>
                         {log}
                       </span>
                     </motion.div>
                   ))}
                 </AnimatePresence>
               </div>
               
               <div className="mt-6 p-4 rounded-xl bg-white/5 border border-white/5 space-y-4">
                  <div className="flex items-center gap-2">
                    <Box className="w-4 h-4 text-muted-foreground" />
                    <span className="text-xs font-semibold">FRACTAL ANALYSIS LOAD</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-center">
                    <div className="p-2 rounded-lg bg-black/20 border border-white/5">
                      <p className="text-[10px] text-muted-foreground">DIMENSION</p>
                      <p className="text-sm font-bold font-mono">1.643</p>
                    </div>
                    <div className="p-2 rounded-lg bg-black/20 border border-white/5">
                      <p className="text-[10px] text-muted-foreground">CONFIDENCE</p>
                      <p className="text-sm font-bold font-mono">94.2%</p>
                    </div>
                  </div>
               </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

function StatNode({ icon: Icon, label, value, sub, color }: any) {
  return (
    <div className="nexus-node p-6 flex flex-col gap-1">
      <div className={`w-8 h-8 rounded-lg mb-2 flex items-center justify-center bg-${color}/10 border border-${color}/20`}>
        <Icon className={`w-4 h-4 text-${color}`} />
      </div>
      <p className="text-[10px] text-muted-foreground uppercase tracking-wider">{label}</p>
      <p className="text-2xl font-bold font-mono">{value}</p>
      <p className="text-[10px] opacity-60 italic">{sub}</p>
    </div>
  );
}
