import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '../components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../components/ui/select';
import { Textarea } from '../components/ui/textarea';
import {
  Search,
  Plus,
  Clock,
  CheckCircle2,
  XCircle,
  Zap,
  User,
  Calendar,
  AlertTriangle,
  Package,
  TrendingDown,
  RefreshCw,
  Trash2,
} from 'lucide-react';
import { useApp } from '../lib/store';
import { toast } from 'sonner';
import { type WorkOrder, type InventoryItem } from '../lib/mock-data';

export function WorkOrders() {
  const { workOrders, assets, technicians, inventory, createWorkOrder, assignWorkOrder, completeWorkOrder } = useApp();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedOrder, setSelectedOrder] = useState<WorkOrder | null>(workOrders[0] || null);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [showAssignDialog, setShowAssignDialog] = useState(false);
  const [assigningToOrder, setAssigningToOrder] = useState<WorkOrder | null>(null);
  const [selectedTech, setSelectedTech] = useState('');
  const [showCompleteDialog, setShowCompleteDialog] = useState(false);
  const [completingOrder, setCompletingOrder] = useState<WorkOrder | null>(null);
  const [completionForm, setCompletionForm] = useState({
    laborHours: 1,
    selectedParts: [] as { id: string; name: string; quantity: number }[],
  });

  const [form, setForm] = useState({
    title: '',
    description: '',
    assetId: '',
    type: 'preventive' as WorkOrder['type'],
    priority: 'medium' as WorkOrder['priority'],
  });

  const filterByStatus = (status: string) => {
    if (status === 'all') return workOrders;
    return workOrders.filter((order) => order.status === status);
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'critical': return 'bg-red-500 text-white';
      case 'high': return 'bg-orange-500 text-white';
      case 'medium': return 'bg-blue-500 text-white';
      case 'low': return 'bg-slate-500 text-white';
      default: return 'bg-slate-500 text-white';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'open': return <Clock className="w-4 h-4" />;
      case 'in-progress': return <AlertTriangle className="w-4 h-4" />;
      case 'completed': return <CheckCircle2 className="w-4 h-4" />;
      case 'cancelled': return <XCircle className="w-4 h-4" />;
      default: return <Clock className="w-4 h-4" />;
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'open': return 'bg-amber-100 text-amber-800';
      case 'in-progress': return 'bg-blue-100 text-blue-800';
      case 'completed': return 'bg-green-100 text-green-800';
      case 'cancelled': return 'bg-slate-100 text-slate-800';
      default: return 'bg-slate-100 text-slate-800';
    }
  };

  const handleCreateWorkOrder = () => {
    if (!form.title || !form.assetId) return;
    const asset = assets.find((a) => a.id === form.assetId);
    createWorkOrder({
      assetId: form.assetId,
      assetName: asset?.name || form.assetId,
      title: form.title,
      description: form.description,
      status: 'open',
      priority: form.priority,
      assignedTo: null,
      completedAt: null,
      type: form.type,
      autoGenerated: false,
    });
    setShowCreateDialog(false);
    setForm({ title: '', description: '', assetId: '', type: 'preventive', priority: 'medium' });
    toast.success('Work order created successfully');
  };

  const handleAssign = () => {
    if (!assigningToOrder || !selectedTech) return;
    assignWorkOrder(assigningToOrder.id, selectedTech);
    setShowAssignDialog(false);
    setAssigningToOrder(null);
    setSelectedTech('');
    // Update the selected order view
    setSelectedOrder((prev) => prev ? { ...prev, assignedTo: selectedTech, status: 'in-progress' } : prev);
    toast.success(`Work order assigned to ${selectedTech}`);
  };

  const openAssignDialog = (order: WorkOrder) => {
    setAssigningToOrder(order);
    setShowAssignDialog(true);
  };

  const openCompleteDialog = (order: WorkOrder) => {
    setCompletingOrder(order);
    setCompletionForm({ laborHours: 1, selectedParts: [] });
    setShowCompleteDialog(true);
  };

  const handleCompleteStatus = () => {
    if (!completingOrder) return;
    completeWorkOrder(completingOrder.id, completionForm.selectedParts, completionForm.laborHours);
    setShowCompleteDialog(false);
    setCompletingOrder(null);
    setSelectedOrder((prev) => prev?.id === completingOrder.id ? { 
      ...prev, 
      status: 'completed', 
      partsUsed: completionForm.selectedParts,
      laborHours: completionForm.laborHours 
    } : prev);
    toast.success('Work order marked as completed');
  };

  const togglePart = (partId: string, partName: string) => {
    setCompletionForm(prev => {
      const exists = prev.selectedParts.find(p => p.id === partId);
      if (exists) {
        return { ...prev, selectedParts: prev.selectedParts.filter(p => p.id !== partId) };
      } else {
        return { ...prev, selectedParts: [...prev.selectedParts, { id: partId, name: partName, quantity: 1 }] };
      }
    });
  };

  const availableTechnicians = technicians.filter((t) => t.status !== 'offline');

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Work Orders</h2>
          <p className="text-slate-500">Manage maintenance tasks and assignments</p>
        </div>
        <Button onClick={() => setShowCreateDialog(true)}>
          <Plus className="w-4 h-4 mr-2" />
          Create Work Order
        </Button>
      </div>

      {/* Search */}
      <Card>
        <CardContent className="p-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <Input
              placeholder="Search work orders..."
              className="pl-9"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
        </CardContent>
      </Card>

      <Tabs defaultValue="all" className="space-y-4">
        <TabsList>
          <TabsTrigger value="all">
            All ({workOrders.length})
          </TabsTrigger>
          <TabsTrigger value="open">
            Open ({filterByStatus('open').length})
          </TabsTrigger>
          <TabsTrigger value="in-progress">
            In Progress ({filterByStatus('in-progress').length})
          </TabsTrigger>
          <TabsTrigger value="completed">
            Completed ({filterByStatus('completed').length})
          </TabsTrigger>
        </TabsList>

        {['all', 'open', 'in-progress', 'completed'].map((tab) => (
          <TabsContent key={tab} value={tab} className="space-y-4">
            <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
              {filterByStatus(tab === 'all' ? '' : tab)
                .filter((order) =>
                  searchTerm
                    ? order.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                      order.assetName.toLowerCase().includes(searchTerm.toLowerCase())
                    : true
                )
                .map((order) => (
                  <Card
                    key={order.id}
                    className={`cursor-pointer transition-shadow hover:shadow-md ${
                      selectedOrder?.id === order.id ? 'ring-2 ring-blue-500' : ''
                    }`}
                    onClick={() => setSelectedOrder(order)}
                  >
                    <CardHeader className="pb-3">
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1">
                            <CardTitle className="text-base truncate">{order.title}</CardTitle>
                          </div>
                          <p className="text-sm text-slate-500">{order.assetName}</p>
                        </div>
                        {order.autoGenerated && (
                          <Badge variant="secondary" className="flex items-center gap-1 flex-shrink-0">
                            <Zap className="w-3 h-3" />
                            AI
                          </Badge>
                        )}
                      </div>
                    </CardHeader>
                    <CardContent className="space-y-3">
                      <p className="text-sm text-slate-600 line-clamp-2">{order.description}</p>

                      <div className="flex items-center gap-2">
                        <Badge className={getPriorityColor(order.priority)}>
                          {order.priority}
                        </Badge>
                        <Badge className={getStatusColor(order.status)} variant="secondary">
                          <span className="mr-1">{getStatusIcon(order.status)}</span>
                          {order.status}
                        </Badge>
                      </div>

                      {order.assignedTo && (
                        <div className="flex items-center gap-2 text-sm text-slate-600">
                          <User className="w-4 h-4" />
                          <span>{order.assignedTo}</span>
                        </div>
                      )}

                      <div className="flex items-center gap-2 text-xs text-slate-500">
                        <Calendar className="w-3 h-3" />
                        <span>
                          Created {new Date(order.createdAt).toLocaleDateString()}
                        </span>
                      </div>

                      <div className="pt-3 border-t border-slate-200 flex gap-2">
                        {!order.assignedTo && order.status === 'open' && (
                          <Button
                            size="sm"
                            variant="outline"
                            className="flex-1"
                            onClick={(e: React.MouseEvent) => {
                              e.stopPropagation();
                              openAssignDialog(order);
                            }}
                          >
                            Assign
                          </Button>
                        )}
                        {order.status === 'in-progress' && (
                          <Button
                            size="sm"
                            className="flex-1"
                            onClick={(e: React.MouseEvent) => {
                              e.stopPropagation();
                              openCompleteDialog(order);
                            }}
                          >
                            Mark Complete
                          </Button>
                        )}
                        <Button
                          size="sm"
                          variant="outline"
                          className="flex-1"
                          onClick={(e: React.MouseEvent) => { e.stopPropagation(); setSelectedOrder(order); }}
                        >
                          View Details
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
            </div>
            {filterByStatus(tab === 'all' ? '' : tab).length === 0 && (
              <div className="text-center py-12 text-slate-400">
                <CheckCircle2 className="w-12 h-12 mx-auto mb-3 opacity-40" />
                <p>No work orders in this category</p>
              </div>
            )}
          </TabsContent>
        ))}
      </Tabs>

      {/* Selected Order Details */}
      {selectedOrder && (
        <Card className="border-blue-200 bg-blue-50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              Selected Work Order: {selectedOrder.id}
              {selectedOrder.autoGenerated && (
                <Badge variant="secondary" className="flex items-center gap-1">
                  <Zap className="w-3 h-3" />
                  AI-Generated
                </Badge>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <p className="text-sm font-medium text-blue-900 mb-1">Asset</p>
                <p className="text-sm text-blue-700">{selectedOrder.assetName}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-blue-900 mb-1">Type</p>
                <Badge variant="outline">{selectedOrder.type}</Badge>
              </div>
              <div>
                <p className="text-sm font-medium text-blue-900 mb-1">Priority</p>
                <Badge className={getPriorityColor(selectedOrder.priority)}>
                  {selectedOrder.priority}
                </Badge>
              </div>
              <div>
                <p className="text-sm font-medium text-blue-900 mb-1">Status</p>
                <Badge className={getStatusColor(selectedOrder.status)} variant="secondary">
                  {selectedOrder.status}
                </Badge>
              </div>
              <div>
                <p className="text-sm font-medium text-blue-900 mb-1">Assigned To</p>
                <p className="text-sm text-blue-700">
                  {selectedOrder.assignedTo || 'Unassigned'}
                </p>
              </div>

              <div>
                <p className="text-sm font-medium text-blue-900 mb-1">Created</p>
                <p className="text-sm text-blue-700">
                  {new Date(selectedOrder.createdAt).toLocaleString()}
                </p>
              </div>
              {selectedOrder.status === 'completed' && (
                <div>
                  <p className="text-sm font-medium text-blue-900 mb-1">Labor Hours</p>
                  <p className="text-sm text-blue-700 font-semibold">{selectedOrder.laborHours || 0} hrs spent</p>
                </div>
              )}
            </div>
            
            {selectedOrder.status === 'completed' && selectedOrder.partsUsed && selectedOrder.partsUsed.length > 0 && (
              <div className="p-3 bg-white border border-blue-200 rounded-lg">
                <p className="text-sm font-medium text-blue-900 mb-2">Parts Consumed</p>
                <div className="flex flex-wrap gap-2">
                  {selectedOrder.partsUsed.map(p => (
                    <Badge key={p.id} variant="secondary" className="bg-blue-100 text-blue-800 border-blue-200">
                      {p.name} (x{p.quantity})
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            <div>
              <p className="text-sm font-medium text-blue-900 mb-1">Description</p>
              <p className="text-sm text-blue-700">{selectedOrder.description}</p>
            </div>

            {/* Action buttons in detail panel */}
            <div className="flex gap-2 flex-wrap">
              {!selectedOrder.assignedTo && selectedOrder.status === 'open' && (
                <Button size="sm" onClick={() => openAssignDialog(selectedOrder)}>
                  <User className="w-4 h-4 mr-2" />
                  Assign Technician
                </Button>
              )}
              {selectedOrder.status === 'in-progress' && (
                <Button
                  size="sm"
                  className="bg-green-600 hover:bg-green-700"
                  onClick={() => {
                    openCompleteDialog(selectedOrder);
                  }}
                >
                  <CheckCircle2 className="w-4 h-4 mr-2" />
                  Mark as Completed
                </Button>
              )}
            </div>

            {selectedOrder.autoGenerated && (
              <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg">
                <div className="flex items-start gap-2">
                  <Zap className="w-4 h-4 text-amber-600 mt-0.5" />
                  <div className="flex-1">
                    <p className="text-sm font-medium text-amber-900 mb-1">
                      AI Predictive Maintenance
                    </p>
                    <p className="text-xs text-amber-700">
                      This work order was automatically generated by the Fi-CMMS fractal analysis
                      engine after detecting equipment health degradation below the configured
                      threshold. The fractal dimension of sensor data indicated structural
                      irregularities requiring immediate inspection.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Create Work Order Dialog */}
      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Plus className="w-5 h-5 text-blue-600" />
              Create Work Order
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="wo-title">Title *</Label>
              <Input
                id="wo-title"
                placeholder="e.g. Quarterly Preventive Maintenance"
                value={form.title}
                onChange={(e) => setForm({ ...form, title: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="wo-asset">Asset *</Label>
              <Select value={form.assetId} onValueChange={(v) => setForm({ ...form, assetId: v })}>
                <SelectTrigger id="wo-asset">
                  <SelectValue placeholder="Select asset..." />
                </SelectTrigger>
                <SelectContent>
                  {assets.map((a) => (
                    <SelectItem key={a.id} value={a.id}>
                      {a.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="wo-type">Type</Label>
                <Select value={form.type} onValueChange={(v) => setForm({ ...form, type: v as WorkOrder['type'] })}>
                  <SelectTrigger id="wo-type">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="preventive">Preventive</SelectItem>
                    <SelectItem value="corrective">Corrective</SelectItem>
                    <SelectItem value="predictive">Predictive</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="wo-priority">Priority</Label>
                <Select value={form.priority} onValueChange={(v) => setForm({ ...form, priority: v as WorkOrder['priority'] })}>
                  <SelectTrigger id="wo-priority">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="low">Low</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                    <SelectItem value="critical">Critical</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="wo-description">Description</Label>
              <Textarea
                id="wo-description"
                placeholder="Describe the maintenance task..."
                rows={3}
                value={form.description}
                onChange={(e) => setForm({ ...form, description: e.target.value })}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateDialog(false)}>Cancel</Button>
            <Button onClick={handleCreateWorkOrder} disabled={!form.title || !form.assetId}>
              Create Work Order
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Assign Technician Dialog */}
      <Dialog open={showAssignDialog} onOpenChange={setShowAssignDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <User className="w-5 h-5 text-blue-600" />
              Assign Technician
            </DialogTitle>
          </DialogHeader>
          {assigningToOrder && (
            <div className="space-y-4">
              <div className="p-3 bg-slate-50 rounded-lg text-sm">
                <p className="font-medium text-slate-900">{assigningToOrder.title}</p>
                <p className="text-slate-500">{assigningToOrder.assetName}</p>
              </div>
              <div className="space-y-2">
                <Label>Select Technician</Label>
                <div className="space-y-2">
                  {availableTechnicians.map((tech) => (
                    <div
                      key={tech.id}
                      onClick={() => setSelectedTech(tech.name)}
                      className={`p-3 rounded-lg border cursor-pointer transition-colors ${
                        selectedTech === tech.name
                          ? 'border-blue-500 bg-blue-50'
                          : 'border-slate-200 hover:border-slate-300'
                      }`}
                    >
                      <div className="flex items-center justify-between">
                        <div>
                          <p className="font-medium text-slate-900">{tech.name}</p>
                          <p className="text-xs text-slate-500">
                            {tech.specialization.slice(0, 2).join(', ')}
                          </p>
                        </div>
                        <Badge
                          className={
                            tech.status === 'available'
                              ? 'bg-green-100 text-green-800'
                              : 'bg-amber-100 text-amber-800'
                          }
                          variant="secondary"
                        >
                          {tech.status} · {tech.activeWorkOrders} active
                        </Badge>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => { setShowAssignDialog(false); setSelectedTech(''); }}>Cancel</Button>
            <Button onClick={handleAssign} disabled={!selectedTech}>
              Assign to {selectedTech || '...'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Completion Details Dialog */}
      <Dialog open={showCompleteDialog} onOpenChange={setShowCompleteDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-green-600" />
              Complete Maintenance Task
            </DialogTitle>
          </DialogHeader>
          {completingOrder && (
            <div className="space-y-4">
              <div className="p-3 bg-slate-50 rounded-lg text-sm">
                <p className="font-medium text-slate-900">{completingOrder.title}</p>
                <p className="text-slate-500">{completingOrder.assetName}</p>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="labor-hours">Labor Hours Spent</Label>
                <Input 
                  id="labor-hours" 
                  type="number" 
                  step="0.5" 
                  min="0.5" 
                  value={completionForm.laborHours}
                  onChange={(e) => setCompletionForm({...completionForm, laborHours: parseFloat(e.target.value) || 0})}
                />
              </div>

              <div className="space-y-2">
                <Label>Inventory Parts Used</Label>
                <div className="border rounded-lg p-2 max-h-40 overflow-y-auto space-y-1">
                  {inventory.map((item: InventoryItem) => (
                    <div 
                      key={item.id} 
                      onClick={() => togglePart(item.id, item.name)}
                      className={`flex items-center justify-between p-2 rounded text-sm cursor-pointer transition-colors ${
                        completionForm.selectedParts.find(p => p.id === item.id)
                        ? 'bg-blue-50 border-blue-200 border'
                        : 'hover:bg-slate-50 border border-transparent'
                      }`}
                    >
                      <span>{item.name}</span>
                      <span className="text-xs text-slate-400">Stock: {item.quantity}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCompleteDialog(false)}>Cancel</Button>
            <Button onClick={handleCompleteStatus} className="bg-green-600 hover:bg-green-700">
              Finalize & Close Order
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
