import { useState } from 'react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { useApp } from '../../lib/store';
import { ClipboardList, AlertTriangle } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';

interface WorkOrderFormProps {
  onSuccess: () => void;
}

export function WorkOrderForm({ onSuccess }: WorkOrderFormProps) {
  const { assets, createWorkOrder } = useApp();
  const [form, setForm] = useState({
    assetId: '',
    title: '',
    description: '',
    priority: 'medium',
    type: 'preventive',
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const selectedAsset = assets.find(a => a.id === form.assetId);
    if (!selectedAsset || !form.title) return;

    await createWorkOrder({
      assetId: form.assetId,
      assetName: selectedAsset.name,
      title: form.title,
      description: form.description,
      priority: form.priority as any,
      status: 'open',
      type: form.type as any,
      autoGenerated: false,
      partsUsed: [],
      assignedTo: null,
      completedAt: null,
      laborHours: 0
    });

    onSuccess();
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 py-2">
      <div className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="asset-select">Target Equipment *</Label>
          <Select onValueChange={(val) => setForm({ ...form, assetId: val })} value={form.assetId}>
            <SelectTrigger>
              <SelectValue placeholder="Select asset to maintain..." />
            </SelectTrigger>
            <SelectContent>
              {assets.map((asset) => (
                <SelectItem key={asset.id} value={asset.id}>
                  {asset.name} ({asset.id})
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label htmlFor="wo-title">Task Title *</Label>
          <Input
            id="wo-title"
            required
            placeholder="e.g. Monthly Calibration"
            value={form.title}
            onChange={(e) => setForm({ ...form, title: e.target.value })}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="wo-desc">Detailed Description</Label>
          <Input
            id="wo-desc"
            placeholder="Describe the maintenance requirements..."
            value={form.description}
            onChange={(e) => setForm({ ...form, description: e.target.value })}
          />
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="wo-priority">Priority Level</Label>
            <Select onValueChange={(val) => setForm({ ...form, priority: val })} value={form.priority}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="low">Low</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="critical">Critical</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="wo-type">Maintenance Type</Label>
            <Select onValueChange={(val) => setForm({ ...form, type: val })} value={form.type}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="preventive">Preventive</SelectItem>
                <SelectItem value="corrective">Corrective</SelectItem>
                <SelectItem value="predictive">Predictive</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>
      <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
        <Button type="submit" className="w-full bg-blue-600 hover:bg-blue-700 text-white">
          <ClipboardList className="w-4 h-4 mr-2" />
          Assign Task
        </Button>
      </div>
    </form>
  );
}
