import express from 'express';
import cors from 'cors';
import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const prisma = new PrismaClient();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

// List all assets
app.get('/', async (req, res) => {
  try {
    const assets = await prisma.asset.findMany({
      include: { workOrders: true }
    });
    // Parse sensorData back to array
    const parsedAssets = assets.map(a => ({
      ...a,
      sensorData: JSON.parse(a.sensorData || '[]')
    }));
    res.json(parsedAssets);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get single asset
app.get('/:id', async (req, res) => {
  try {
    const asset = await prisma.asset.findUnique({
      where: { id: req.params.id },
      include: { workOrders: true, sensorReadings: true }
    });
    if (!asset) return res.status(404).json({ message: 'Asset not found' });
    asset.sensorData = JSON.parse(asset.sensorData || '[]');
    res.json(asset);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Update health score
app.patch('/:id/health', async (req, res) => {
  const { healthScore, sensorData } = req.body;
  const THRESHOLD = 65;

  try {
    const assetId = req.params.id;
    const { diagnostics } = req.body;
    
    const updateData = { healthScore };
    if (sensorData) updateData.sensorData = JSON.stringify(sensorData);
    
    const asset = await prisma.asset.update({
      where: { id: assetId },
      data: updateData
    });

    // TRIGGER: Auto-generate Predictive Work Order if health is critical
    if (healthScore < THRESHOLD) {
      console.log(`[TRIGGER] Health score ${healthScore}% is critical for ${assetId}.`);
      
      try {
        // Create the work order in the Work Order Service
        const woResponse = await fetch('http://localhost:3002/', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            id: `WO-AI-${assetId}-${Date.now().toString().slice(-4)}`,
            assetId: asset.id,
            assetName: asset.name,
            title: 'Predictive: Critical Health Anomaly',
            description: diagnostics?.origin_analysis || `AI Engine detected health score of ${healthScore}%. Immediate inspection required.`,
            priority: 'critical',
            type: 'predictive',
            autoGenerated: true,
            aiDiagnosticReport: diagnostics ? JSON.stringify(diagnostics) : null
          })
        });

        if (woResponse.ok) {
          console.log(`[SUCCESS] Predictive Work Order generated for ${assetId}`);
        } else {
          console.log(`[WARN] Failed to trigger work order. Service responded with ${woResponse.status}`);
        }
      } catch (triggerError) {
        console.error('[ERROR] Inter-service communication failed:', triggerError.message);
      }
    }

    res.json(asset);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Create asset
app.post('/', async (req, res) => {
  try {
    const data = {
      ...req.body,
      sensorData: JSON.stringify(req.body.sensorData || []),
      lastMaintenance: new Date(req.body.lastMaintenance),
      nextMaintenance: new Date(req.body.nextMaintenance),
      installDate: new Date(req.body.installDate),
    };
    const asset = await prisma.asset.create({ data });
    res.status(201).json(asset);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.listen(PORT, () => {
  console.log(`Asset Service running on port ${PORT}`);
});
